name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line printing gh workflow directory.
        run: echo $GITHUB_WORKSPACE 
        #/home/runner/work/GithubActionsExercisesPrep/GithubActionsExercisesPrep

      - name: Whoami.
        run: whoami

      - name: Check env.
        run: printenv

      - name: Run a multi-line script
        run: | 
          echo This is a multi
          echo line command.
