name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Code checkout.
        uses: actions/checkout@v4

      - name: Run a one-line printing gh checkout directory.
        run: echo $GITHUB_WORKSPACE 
        #/home/runner/work/GithubActionsExercisesPrep/GithubActionsExercisesPrep
        
      - name: Run a one-line listing dir for all workflows.
        run: ls $RUNNER_WORKSPACE

      - name: Run a one-line listing dir where whole gh repo code is checked-out.
        run: ls $GITHUB_WORKSPACE
        
      - name: Whoami.
        run: whoami

      - name: Check env. Use these in workflows. 
        run: printenv

      - name: Run a multi-line script
        run: | 
          echo This is a multi
          echo line command.

      - name: Set up Node.js. 
        uses: actions/setup-node@v2
        with: #see input values for the action. Generally, all input actions are set wth with.
          node-version: '14'
      
      - name: See where those are installed. Look at docs of actions/setup-node@v2.
        run: |
          echo "This action is creating a local .npmrc file on the runner that configures the default registry and scopes"
          echo "This action can take a gh authentication token for accessing private repos and publishing to pckg mngmnt."

      - name: Echo .npmrc file.
        run: |
          echo "LIST /home/runner:"
          ls -la /home/runner/
          echo "LIST work:"
          ls /home/runner/work
          echo "LIST runners:"
          ls /home/runner/runners
          echo "LIST factory:"
          ls /home/runner/factory
          echo "LIST .nvm"
          ls -la /home/runner/.nvm/
          echo "CAT .npmrc:"
          cat /home/runner/.nvm/.npmrc

      - name: Check if there is docker preinstalled bc these actions are containers.
        run: docker -v

      - name: List docker images.
        run: docker image ls 

      - name: List docker containers.
        run: docker ps -a

  #    - name: Install dependencies.
  #      run: |
  #        pwd
  #       npm install

  #    - name: Run test.
  #     run: |
  #        pwd
  #        npm test
      - name: Check how to use if/else conditions.
        run: echo "This step runs because the condition is true."
        if: github.ref == 'refs/heads/main' #Condition to check if branch is main

      - name: Check for false condition.
        run: echo "This step runs because condition is false."
        if: github.ref != 'refs/heads/main' #else statement
        

        














        
