name: Contexts

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  contexts-exercise:
    runs-on: ubuntu-latest

    steps:

    - name: Echo the top-level context available.
      run: echo "${{ github }}"

    - name: Echo specific Github context properties.
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "SHA: ${{ github.sha }}"
