name: DockerHub Login

on:
  push:
    branches: main

jobs:
  login_job:
    runs-on: ubuntu-latest
    steps:
#      - name: Login to DockerHub with username and password (NOT RECOMMENDED).
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_GMAIL }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout a code into working directory.
        uses: actions/checkout@v4
        
      - name: Login to DockerHub with generated Personal Access Token.
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_GMAIL }}
          password: ${{ secrets.DOCKERHUB_PAT }}
        #this is the recommended way for accessing 

      - name: Extract metadata from Git reference nad GitHub events. 
        id: meta #add this id just to reference this step in further steps
        uses: docker/metadata-action@v5
        with:
          images: |
            mihailomahovac/repo_gha     #name of a remote repo
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
        #u can use this steps with labels:${{ steps.meta.outputs.labels }}
        
       
      - name: Build and push to DockerHub.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
 #   env:
 #     ACTION_SETUP_DEBUG: true # setting additional environment variable to debug more information

 #workflow commands in action to configure runner env
 #configure a workflow to use a workfow that is being used from current workflow
 #see caching used in docker build

 #using GitHub environment file 
      - name: Use environment variables file on  runner! Set runner environemnt variables with $GITHUB_ENV file. 
        run: |
          echo "DEMO_ENV='This is a demo'" >> $GITHUB_ENV


# publish custom github action: oowner.proj_folder@v1.2.3 
