name: DockerHub Login

on:
  push:
    branches: main

jobs:
  login_job:
    runs-on: ubuntu-latest
    steps:
#      - name: Login to DockerHub with username and password (NOT RECOMMENDED).
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_GMAIL }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout a code into working directory.
        uses: actions/checkout@v4
        

      - name: Login to DockerHub with generated Personal Access Token.
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_GMAIL }}
          password: ${{ secrets.DOCKERHUB_PAT }}
        #this is the recommended way for accessing 

      - name: Extract metadata from Git reference nad GitHub events. 
        id: meta #add this id just to reference this step in further steps
        uses: docker/metadata-action@v5
        #u can use this steps with labels:${{ steps.meta.outputs.labels }}
      - name: Build and push to DockerHub.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: Mihailo222/app:1.0.0
