name: DockerHub Login

on:
  push:
    branches: main

jobs:
  login_job:
    runs-on: ubuntu-latest
    steps:
#      - name: Login to DockerHub with username and password (NOT RECOMMENDED).
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_GMAIL }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to DockerHub with generated Personal Access Token.
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_GMAIL }}
          password: ${{ secrets.DOCKERHUB_PAT }}
        #this is the recommended way for accessing 

      - name: Extract metadata from Git reference nad GitHub events. 
        uses: docker/metadata-action@v5
        
