name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        pwd
        npm install

    - name: Run Test Suite.
      run: npm test
      
  start-server:
    runs-on: ubuntu-latest
    needs: test #this job is being executed after runs-on job has been executed successfully

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Start server
      run: |
        pwd
        node app.js






  
